generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Fatipmov
    theme:            cidesaGenerator

    fields:
      desmov: { name: Descripci贸n, validate: Vstring_1_50, msj_error: Debe insertar la descripci贸n del tipo de movimiento }
      nomabr: { name: Nombre Abreviado, validate: Vstring_1_4 }
      debcre: { name: Tipo}
      codcta: { name: Cta. Contable Asociada}
      codtiptra: { name: Tipo de Transacci贸n}

    list:
      title: Tipos de Movimiento
      display: [=desmov, nomabr, debcre]
      filters: [desmov]
      object_actions:
       _edit:        ~
       _delete:        ~
      max_per_page:	  10
      sort:    desmov

    edit:
      title: Definici贸n de Tipo de Movimiento
      display:
        "NONE": [desmov, nomabr, debcre, _codcta, codtiptra]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~
